# Generated by Django 4.2.5 on 2023-10-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_chat_alter_message_user_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message'),
        ),
    ]
