# Generated by Django 4.2.7 on 2024-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_reply_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
    ]
