# Generated by Django 4.2.7 on 2024-04-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_current_city_profile_current_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
